version: "3.3"
services:
  web:
    build: ./PisApp
    ports:
      - "5001:9000"
    environment:
      host: 'mysql-db'
    restart: always
    depends_on:
      - "mysql-db"
    networks:
      sirs-merchantwebsite_app_net:
        ipv4_address: 172.18.1.2
  mysql-db:
    build: ./Database
    networks:
      sirs-merchantwebsite_app_net:
        ipv4_address: 172.18.1.4
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: 'testpis'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usr'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
  nginx:
    build: ./nginx
    ports: 
      - '80'
      - '8765'
      - '8755'
    expose:
      - '80'
      - '8765'
      - '8755'
    volumes:
      - nginx:/var/lib/nginx
    networks:
      sirs-merchantwebsite_app_net:
        ipv4_address: 172.18.1.3
  # Names our volume
volumes:
  my-db:
  nginx:
networks:
  sirs-merchantwebsite_app_net:
    external: true

